select C.CONSTITUENT_ID, C.AGE, C.GENDER, C.STATE, C.MARRIED, 
count(F.FAMILY_ID), count(E.EVENT_ATTENDEE_ID), count(V.VOLUNTEER_ID), sum(T.AMOUNT)
from CONSTITUENT C
left join EVENT_ATTENDEE E on C.CONSTITUENT_ID = E.CONSTITUENT_ID
left join FAMILY F on C.CONSTITUENT_ID = F.CONSTITUENT_ID
left join TRANSACTIONS T on C.CONSTITUENT_ID = T.CONSTITUENT_ID
left join VOLUNTEER V on C.CONSTITUENT_ID = V. VOLUNTEER_ID
group by CONSTITUENT_ID;